# Generated by Django 2.1.7 on 2019-06-08 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirbMeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme_image', models.ImageField(upload_to='birb_meme')),
                ('description', models.TextField()),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemeCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemeEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme_eval', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BirbMeme.MemeCreator')),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BirbMeme.BirbMeme')),
            ],
        ),
        migrations.AddField(
            model_name='birbmeme',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BirbMeme.MemeCreator'),
        ),
    ]
