# Generated by Django 2.2 on 2019-06-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BirbMeme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memeevaluation',
            name='meme_eval',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
    ]
